"""
LiveDriftMonitor -- auto-flip safety valve for the promoted sprint v1 config.

Compares each closed trade's realized pnl_bps against the shadow
expectation for its (direction, UTC session) bucket. Appends z-scores
to a rolling window persisted on disk. Triggers a persistent safety
valve marker (and disables sprint flags + reverts leverage in the
caller) when cumulative z falls below an adverse threshold.

Design choices:
  - Only ADVERSE drift disables. Positive drift is noted, not acted on.
  - Idempotent: once the valve marker is on disk, subsequent check_trade
    calls return {"fired": False, "reason": "already_disabled"} and do
    not re-write the marker.
  - Fallback bucketing: if the primary (direction, session) bucket has
    count < 5, use the direction-only fallback.
  - Persists state across restarts so the window survives bot reboots.

File layout (all under state_dir):
  shadow_expectation.json  -- input; generated by shadow_expectation_generator.py
  live_drift_monitor.json  -- output; rolling z-score window (10 trades by default)
  safety_valve.json        -- output; persistent marker when tripped
"""
import json
import os
from datetime import datetime, timezone
from pathlib import Path


class LiveDriftMonitor:
    DEFAULT_WINDOW = 10
    # threshold = -2 * sqrt(N); for N=10 that's ~= -6.3246.
    # "+2σ in the adverse direction" on a sum of N unit-z iid scores
    # has std = sqrt(N), so threshold = -2 * std = -2 * sqrt(N).
    @staticmethod
    def default_threshold(window_size):
        return -2.0 * (window_size ** 0.5)

    BUCKET_SESSIONS = [(0, 8, "asia"), (8, 16, "europe"), (16, 24, "americas")]

    def __init__(self, state_dir, window_size=DEFAULT_WINDOW, threshold=None):
        self.state_dir = Path(state_dir)
        self.window_size = window_size
        self.threshold = (threshold if threshold is not None
                          else self.default_threshold(window_size))
        self.shadow_file = self.state_dir / "shadow_expectation.json"
        self.drift_file  = self.state_dir / "live_drift_monitor.json"
        self.valve_file  = self.state_dir / "safety_valve.json"
        self._shadow = None
        self._window = {"z_scores": [], "trade_order_ids": []}
        self._load()

    # ------------------------------------------------------------
    # loading
    # ------------------------------------------------------------
    def _load(self):
        if self.shadow_file.exists():
            try:
                self._shadow = json.loads(self.shadow_file.read_text())
            except Exception:
                self._shadow = None
        if self.drift_file.exists():
            try:
                self._window = json.loads(self.drift_file.read_text())
                self._window.setdefault("z_scores", [])
                self._window.setdefault("trade_order_ids", [])
            except Exception:
                pass

    # ------------------------------------------------------------
    # bucket classification
    # ------------------------------------------------------------
    @classmethod
    def bucket_for(cls, direction, iso_ts):
        """Return (primary_bucket_key, direction_key) from a trade record."""
        d = "long" if direction == 1 else "short"
        try:
            dt = datetime.fromisoformat(iso_ts)
            if dt.tzinfo is not None:
                dt = dt.astimezone(timezone.utc)
            h = dt.hour
        except Exception:
            h = 0
        sess = "asia"
        for lo, hi, name in cls.BUCKET_SESSIONS:
            if lo <= h < hi:
                sess = name; break
        return f"{d}_{sess}", d

    def _resolve_stats(self, direction, iso_ts):
        """Return (stats_dict_or_None, used_bucket_label)."""
        if self._shadow is None:
            return None, None
        primary, fallback = self.bucket_for(direction, iso_ts)
        buckets = self._shadow.get("buckets", {})
        fb_map  = self._shadow.get("fallback_by_direction", {})
        stats = buckets.get(primary)
        used = primary
        if not stats or stats.get("count", 0) < 5:
            stats = fb_map.get(fallback)
            used = fallback + " (fallback)"
        if not stats or (stats.get("std_bps") or 0) <= 0:
            return None, None
        return stats, used

    # ------------------------------------------------------------
    # state query helpers
    # ------------------------------------------------------------
    def is_disabled(self):
        return self.valve_file.exists()

    def window_size_current(self):
        return len(self._window.get("z_scores", []))

    def cumulative_z(self):
        return float(sum(self._window.get("z_scores", [])))

    def window_full(self):
        return self.window_size_current() >= self.window_size

    def should_auto_disable(self):
        """True iff a fresh trigger condition is met right now. Once the
        valve marker is written, returns False (idempotent guard)."""
        if self.is_disabled():
            return False
        if not self.window_full():
            return False
        return self.cumulative_z() < self.threshold

    # ------------------------------------------------------------
    # main entry point
    # ------------------------------------------------------------
    def check_trade(self, trade):
        """Process one closed trade. Returns:
          {
            z: float|None,
            cum_z: float|None,
            fired: bool,
            bucket: str|None,
            reason: str|None,   # only set when nothing happened
          }
        Writes the valve marker if the trigger condition is newly met.
        Idempotent once tripped."""
        if self.is_disabled():
            return {"z": None, "cum_z": None, "fired": False,
                    "bucket": None, "reason": "already_disabled"}
        if self._shadow is None:
            return {"z": None, "cum_z": None, "fired": False,
                    "bucket": None, "reason": "no_shadow_expectation"}

        direction = trade.get("direction")
        iso_ts    = trade.get("time")
        if direction is None or iso_ts is None:
            return {"z": None, "cum_z": None, "fired": False,
                    "bucket": None, "reason": "malformed_trade"}

        stats, used_bucket = self._resolve_stats(direction, iso_ts)
        if stats is None:
            return {"z": None, "cum_z": None, "fired": False,
                    "bucket": None, "reason": "invalid_bucket_stats"}

        realized = trade.get("pnl_bps", 0.0)
        z = (realized - stats["mean_pnl_bps"]) / stats["std_bps"]

        # Append to rolling window (trim from the front)
        zs = self._window.setdefault("z_scores", [])
        ids = self._window.setdefault("trade_order_ids", [])
        zs.append(float(z))
        ids.append(trade.get("order_id"))
        if len(zs) > self.window_size:
            self._window["z_scores"] = zs[-self.window_size:]
            self._window["trade_order_ids"] = ids[-self.window_size:]
        self._window["last_bucket"] = used_bucket
        self._window["last_z"] = float(z)
        self._window["last_realized_pnl_bps"] = realized
        self._window["last_expected_mean_bps"] = stats["mean_pnl_bps"]
        self._window["last_expected_std_bps"]  = stats["std_bps"]
        self._window["updated_at"] = datetime.now(timezone.utc).isoformat()

        self._persist_window()

        cum_z = self.cumulative_z()
        fired = self.should_auto_disable()
        if fired:
            self._write_valve_marker(cum_z)
        return {"z": float(z), "cum_z": float(cum_z), "fired": bool(fired),
                "bucket": used_bucket, "reason": None}

    # ------------------------------------------------------------
    # persistence
    # ------------------------------------------------------------
    def _persist_window(self):
        tmp = str(self.drift_file) + ".tmp"
        with open(tmp, "w") as f:
            json.dump(self._window, f, indent=2)
        os.replace(tmp, str(self.drift_file))

    def _write_valve_marker(self, cum_z):
        marker = {
            "auto_disabled_at": datetime.now(timezone.utc).isoformat(),
            "cumulative_z": float(cum_z),
            "threshold": float(self.threshold),
            "window_size": self.window_size,
            "z_scores_at_trip": list(self._window.get("z_scores", [])),
            "trade_order_ids_at_trip": list(self._window.get("trade_order_ids", [])),
            "disabled_flags": ["f3c_enabled", "timeout_trail_enabled",
                                "e3_time_decay_sl_enabled"],
            "leverage_reverted_to": 10,
            "reason": (f"cumulative z over last {self.window_size} trades "
                       f"({cum_z:+.2f}) below adverse threshold "
                       f"({self.threshold:+.2f})"),
        }
        with open(self.valve_file, "w") as f:
            json.dump(marker, f, indent=2)

    # ------------------------------------------------------------
    # management
    # ------------------------------------------------------------
    def reset_window(self):
        """Delete the rolling window (used when promoting to a new config
        stage or regenerating shadow expectation)."""
        if self.drift_file.exists():
            self.drift_file.unlink()
        self._window = {"z_scores": [], "trade_order_ids": []}

    def clear_valve(self):
        """Manually clear the safety-valve marker. Caller should only do
        this after a documented postmortem."""
        if self.valve_file.exists():
            self.valve_file.unlink()
